# Importing the library

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.0.0


TensorFlow was initially created in a static graph paradigm – in other words, first all the operations and variables are defined (the graph structure) and then these are compiled within the tf.Session object. There is now the option to build graphs on the fly using the TensorFlow Eager framework

# Tensorflow using Eager Framework

With tensorflow eager execution we can immediately access the results of the operation

# Defining a Constant with data type string 

In [3]:
hello = tf.constant("Hello ")
world = tf.constant("World")

In [4]:
print(type(hello))
print(type(world))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
print(hello + world)

tf.Tensor(b'Hello World', shape=(), dtype=string)


since the eager execution is enabled we can access the results of the operation hello + world = b'Hello World' as shown above

Here the b in front of Hello and World represents a byte literal

# Defining a constant with int data type

In [6]:
node1 = tf.constant(3)
node2 = tf.constant(4)

In [7]:
print(node1)
print(node2)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [8]:
print(node1 * node2)

tf.Tensor(12, shape=(), dtype=int32)


if we disable eager execution then the output would be-

Tensor("Mul:0", shape=(), dtype=int32)

Also by default the eager execution in tensorflow 2.0 is enabled

### Note: Placeholders are not compatible with eager execution.


In [9]:
x = tf.compat.v1.placeholder(tf.float32, shape=(1024, 1024))

RuntimeError: tf.placeholder() is not compatible with eager execution.

# Disabling Eager Execution

In [11]:
tf.compat.v1.disable_eager_execution()

the above command is used to disable the eager execution

OR

you can also disable the eager execution using the following commands-

import tensorflow.compat.v1 as tf

tf.disable_eager_execution()

# Sessions in Tensorflow 

A session allows to execute graphs or part of graphs. It allocates resources (on one or more machines) for that and holds the actual values of intermediate results and variables.

# Building a graph

In [12]:
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

#  Launching the graph in a session.


In [14]:
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`

In [15]:
print(sess.run(c))

30.0


In [16]:
sess.close()

# Creating a matrix

In [17]:
fill_mat = tf.fill((4,4), 10)

In [18]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

# Creating a session as a context manager 

In [21]:
with tf.compat.v1.Session() as sess:
    print(sess.run(fill_mat))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


# Zeros Matrix

In [22]:
zeros = tf.zeros((4,4))

In [24]:
with tf.compat.v1.Session() as sess:
    print(sess.run(zeros))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Getting the shape of a constant

In [25]:
a = tf.constant([[1, 2],
                [3, 4]])

In [26]:
a.get_shape()

TensorShape([2, 2])

# eval( ) function of tensorflow 

In [27]:
b = tf.constant([ [10], [100]])

In [28]:
result = tf.matmul(a, b)

In [33]:
sess = tf.compat.v1.Session()

In [34]:
result.eval(session = sess)

array([[210],
       [430]], dtype=int32)

# Interactive Session in tensorflow

The only difference between Session and an InteractiveSession is that InteractiveSession makes itself the default session so that you can call run() or eval() without explicitly calling the session.

This can be helpful if you experiment with TF in python shell or in Jupyter notebooks, because it avoids having to pass an explicit Session object to run operations.

In [36]:
sess = tf.compat.v1.InteractiveSession()

In [37]:
import numpy as np

In [38]:
x = np.arange(0, 5, 0.1)
y = ((x**3) - (4*x**2) - (2*x) + 2)

In [40]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [39]:
y

array([  2.   ,   1.761,   1.448,   1.067,   0.624,   0.125,  -0.424,
        -1.017,  -1.648,  -2.311,  -3.   ,  -3.709,  -4.432,  -5.163,
        -5.896,  -6.625,  -7.344,  -8.047,  -8.728,  -9.381, -10.   ,
       -10.579, -11.112, -11.593, -12.016, -12.375, -12.664, -12.877,
       -13.008, -13.051, -13.   , -12.849, -12.592, -12.223, -11.736,
       -11.125, -10.384,  -9.507,  -8.488,  -7.321,  -6.   ,  -4.519,
        -2.872,  -1.053,   0.944,   3.125,   5.496,   8.063,  10.832,
        13.809])

In [43]:
y_noise = tf.add(y,np.random.normal(0, 1.5, size=(len(x),)))

In [44]:
y_noise

<tf.Tensor 'Add:0' shape=(50,) dtype=float64>

In [45]:
sess.run(y_noise)

array([ -0.17697184,   1.74890828,   0.37065966,   4.82192114,
         2.0103875 ,   0.05043963,  -1.48043303,  -3.16415012,
        -1.42501836,  -1.10728586,  -0.88217997,  -2.04825938,
        -3.90047846,  -5.43545737,  -8.82924791,  -6.91644696,
        -7.09004629,  -4.87078687,  -9.55481266, -11.08602311,
        -9.75161308, -11.61491331, -11.33534118,  -9.30780451,
       -13.72811522, -11.94085148, -12.06431115, -16.11238418,
       -13.8609758 , -13.89660885, -14.03936343, -11.72171217,
       -13.92861502, -13.50505398, -13.60823486, -11.97076128,
       -11.02290494,  -9.42483156, -11.68630644,  -9.15919614,
        -4.87748473,  -6.82976954,  -3.92803696,  -1.07064365,
         1.17646543,   1.80684945,   7.87590828,   5.07763498,
         8.83427307,  13.68003016])

In [46]:
node3 = tf.constant(3.0)

In [47]:
node4 = tf.constant(6.0)

In [48]:
print(node3)
print(node4)

Tensor("Const_4:0", shape=(), dtype=float32)
Tensor("Const_5:0", shape=(), dtype=float32)


In [51]:
output = tf.add(node3, node4)

In [52]:
sess.run(output)

9.0

# Placeholders in Tensorflow

placeholders are initially empty and are used to feed in the actual training example

However they need a declared expected data type (tf.int32) with an optional shape argument

In [55]:
a = tf.compat.v1.placeholder(tf.float32)
b = tf.compat.v1.placeholder(tf.float32)

In [56]:
adder_node = a + b

In [57]:
sess.run(adder_node, {a:[1,2,3], b:[3,4,5]}) #feeds to the placeholders a & b

array([4., 6., 8.], dtype=float32)

# Variables in Tensorflow

Variables are manipulated via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor.

In [59]:
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x = tf.compat.v1.placeholder(tf.float32)

In [60]:
linear_model = W * x + b

To initialise all the varibles in Tensorflow program you must explicitly call a special operation which is defined below

In [63]:
init = tf.compat.v1.global_variables_initializer()

In [65]:
sess.run(init)

In [66]:
sess.run(linear_model, {x:[1,2,3,4]})

array([0.        , 0.3       , 0.6       , 0.90000004], dtype=float32)